name: CI use LocalStack

on:
  push:
    branches:
      - main
env:
  AWS_ACCESS_KEY_ID: dummy
  AWS_SECRET_ACCESS_KEY: dummy
  AWS_DEFAULT_REGION: ap-northeast-1
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('.github/workflows/ci.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aws-sam-cli-local
          pip install terraform-local

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Deploy LocalStack
        run: |
          docker compose up -d

      - name: Cache SAM Local build
        uses: actions/cache@v3
        with:
          path: sam/.aws-sam/build
          key: ${{ runner.os }}-samlocal-${{ hashFiles('sam/template.yaml') }}
          restore-keys: |
            ${{ runner.os }}-samlocal-

      - name: Deploy samlocal
        working-directory: ./sam
        run: |
          samlocal build
          samlocal deploy --stack-name samlocal --resolve-s3

      - name: Deploy terraform
        working-directory: ./tf
        run: |
          tflocal init 
          tflocal apply -auto-approve

      - name: Run tests
        working-directory: ./sam
        run: |
          go test ./...
